### ISSUE TITLE
backlog4jのようにプログラムからapi keyを設定する方法がほしい

### ISSUE THREAD

**Issue by kitadakyou** [kitadakyou/PyBacklogPy#1]
backlog4jでは、次のような感じになります。

```
# If your space is in backlog.com
BacklogConfigure configure = new BacklogComConfigure("yourSpaceId").apiKey("yourApiKey");

# If your space is in backlogtool.com
BacklogConfigure configure = new BacklogToolConfigure("yourSpaceId").apiKey("yourApiKey");

# If your space is in backlog.jp
BacklogConfigure configure = new BacklogJpConfigure("yourSpaceId").apiKey("yourApiKey");
https://github.com/nulab/backlog4j
```

こちらのライブラリでも configure を生成して次のように与える形もどうでしょうか？
```
wiki_api = Wiki(configure)
```

**Comment by kitadakyou** [comment]
#3 対応のため、大変お手数なのですがブランチを変更させていただきました。

**Comment by kitadakyou** [comment]
> 使ってみたいのですが、 pip install pybacklogpy だと 0.9しか入らないようなので 0.10 としてリリースしてもらえないでしょうか。

申し訳ありません。修正の度にリリースを行うとバージョンが膨らんでしまうため、GitHub から直接インストールをお願いできますでしょうか。

以下のコマンドでインストールできます。
```
pip install git+https://github.com/kitadakyou/PyBacklogPy.git
```

上記につきまして、不明点がございましたら、ご連絡いただければと思います。

**Comment by yuichi0301** [comment]
@kitadakyou 
masterブランチのREADMEに `pip install pybacklogpy` でインストールする手順で次の内容が書いてあるので、ユーザーさんが使うときにうまくいかないってことにならないですかね？

```python
from pybacklogpy.BacklogConfigure import BacklogComConfigure
from pybacklogpy.Issue import Issue

# Configure クラスのインスタンスを生成
config = BacklogComConfigure(space_key='kitadakyou',
                             api_key='qwertyuiopasdfghjklzxcvbnmqazwsxedcrfvtgbyhnujmikolp')


issue_api = Issue(config)  # API を呼ぶクラスのコンストラクタ引数として Configure クラスのインスタンスは使用可能 
response = issue_api.get_issue_list()

issue_api_2 = Issue()  # Configure クラスを渡さなかった場合は、次で紹介する設定ファイルの情報を読みに行く
response_2 = issue_api_2.get_issue_list()
```

**Comment by kitadakyou** [comment]
@yuichi0301 

Backlogさんのドキュメントに載るまでダウンロードされないだろうと勝手に考えておりましたが、公開している以上、そんなことはないですね。。ご指摘ありがとうございました。
今後、ドキュメントとPyPI上のリリースで齟齬が出ないように気をつけます。

今し方、PyPI上の物を `0.10` に上げましたので、 `pip install` したものでも、プログラム上からキーやシークレットの設定が出来るようになりました。

参考までに、私の方で確認したコードは以下のようになります。

```
from pybacklogpy.BacklogConfigure import BacklogComConfigure
from pybacklogpy.User import User

config = BacklogComConfigure(
    api_key='[api-key]',
    space_key='[my-space]'
)
user = User(config)
print(user.get_user_list().text)
```

**Comment by yuichi0301** [comment]
@kitadakyou 
問題なさそうです！
こちらクローズしますね！

**Comment by yuichi0301** [comment]
@kitadakyou

READMEに書いてあるコードをそのまま試すとこの部分で落ちるので、この部分を[設定ファイルで指定する場合]の項目に移動できますか？
```python
issue_api_2 = Issue()  # Configure クラスを渡さなかった場合は、次で紹介する設定ファイルの情報を読みに行く
response_2 = issue_api_2.get_issue_list()
```

```
~/D/test ❯❯❯ python test.py
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    issue_api_2 = Issue()  # Configure クラスを渡さなかった場合は、次で紹介する設定ファイルの情報を読みに行く
  File "/Users/yuichi/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/pybacklogpy/Issue.py", line 13, in __init__
    self.rs = RequestSender(_config)
  File "/Users/yuichi/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/site-packages/pybacklogpy/modules.py", line 31, in __init__
    self.api_url = 'https://{backlog_host}/api/v2/'.format(backlog_host=config_file['backlog']['Host'])
  File "/Users/yuichi/.anyenv/envs/pyenv/versions/3.6.5/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
```

**Comment by kitadakyou** [comment]
@yuichi0301 
すみません、こちら修正いたしました。 #6 の PR になります。

**Comment by yuichi0301** [comment]
@kitadakyou こちら問題なさそうです。クローズしていただいて問題ありません！

**Comment by kitadakyou** [comment]
@yuichi0301 
ご確認ありがとうございました。クローズいたします。
